version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node_bayaria_api
    image: node_bayaria_api
    restart: "no"
    ports:
      - "3320:3320"
    networks:
      - bayaria_network
    command: bash -c "npm run build:docker && cd build && node app/server.js"
networks:
  bayaria_network:
    name: bayaria_network
