version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nodejs_gdi
    image: nodejs_gdi
    restart: "no"
    ports:
      - "3320:3320"
    networks:
      - gdi_network
    depends_on:
      - db
    command: bash -c "npm run build:docker && cd build && node server.js"
  db:
    container_name: postgres_gdi
    image: postgres:13.3
    restart: "no"
    environment:
      POSTGRES_PASSWORD: 713320
    ports:
      - "7133:5432"
    networks:
      - gdi_network
networks:
  gdi_network:
    name: gdi_network
